I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/game_initialize.rpy", line 2, in script
    init python:
  File "game/game_initialize.rpy", line 2, in script
    init python:
  File "game/game_initialize.rpy", line 20, in <module>
    game.dooms.append( slasher )
AttributeError: 'Game' object has no attribute 'dooms'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 560, in main
    renpy.game.context().run(node)
  File "game/game_initialize.rpy", line 2, in script
    init python:
  File "game/game_initialize.rpy", line 2, in script
    init python:
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/game_initialize.rpy", line 20, in <module>
    game.dooms.append( slasher )
AttributeError: 'Game' object has no attribute 'dooms'

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
RENPY 1.0
Sun Jan 30 14:47:22 2022
